### ISSUE TITLE
meson.build version does not match source-tag

### ISSUE THREAD

**Issue by hellsworth** [ubuntu/gnome-mahjongg#4]
@sergio-costas In the [meson.build patch](https://github.com/ubuntu/gnome-mahjongg/blob/stable/patches/01-fix-meson-syntax.diff#L103) why are we setting the version to '3.38.0' instead of '3.38.3'? The yaml currently sets the source-tag to 3.38.3. Does this mean that every time we bump the version, this patch needs to be updated too?

Jesus found this issue when testing the new snap in --candidate :)

**Comment by sergio-costas** [comment]
My fault. Fixing it.
